amcl:
  ros__parameters:
    use_sim_time: true

bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_link

controller_server:
  ros__parameters:

    use_sim_time: true

    controller_frequency: 10.0

    min_x_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001

    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"

      debug_trajectory_details: true

      min_vel_x: 0.0
      max_vel_x: 0.20

      max_vel_theta: 1.0

      acc_lim_x: 2.5
      acc_lim_theta: 3.2

      decel_lim_x: -2.5

      vx_samples: 20
      vtheta_samples: 40

      sim_time: 2.0

      linear_granularity: 0.05
      angular_granularity: 0.025

      transform_tolerance: 0.2

      xy_goal_tolerance: 0.20
      yaw_goal_tolerance: 0.20

      critics:
        [
          "RotateToGoal",
          "Oscillation",
          "BaseObstacle",
          "GoalAlign",
          "PathAlign",
          "PathDist",
          "GoalDist"
        ]

      BaseObstacle.scale: 0.08

      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0

      PathDist.scale: 32.0
      GoalDist.scale: 24.0

local_costmap:
  local_costmap:
    ros__parameters:

      use_sim_time: true

      global_frame: odom
      robot_base_frame: base_link

      rolling_window: true

      width: 6
      height: 6

      resolution: 0.05

      robot_radius: 0.22

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"

        observation_sources: scan

        scan:
          topic: /scan
          data_type: "LaserScan"

          marking: true
          clearing: true

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"

        inflation_radius: 0.45

global_costmap:
  global_costmap:
    ros__parameters:

      use_sim_time: true

      global_frame: map
      robot_base_frame: base_link

      resolution: 0.05

      robot_radius: 0.22

      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"

planner_server:
  ros__parameters:

    use_sim_time: true

    expected_planner_frequency: 20.0

    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

      tolerance: 0.5
      use_astar: false

map_server:
  ros__parameters:
    use_sim_time: true
